class_name TutorialController
extends Node
## Manages tutorial phase progression with typed instructions.
## Each phase has an objective, a success condition, and instruction text.

signal phase_completed(phase_idx: int)
signal tutorial_complete

enum Phase {
	MOVE,
	WEAPONS,
	ENERGY_DRAIN,
	POWER_CORES,
	HEAT,
	DEACTIVATE,
	FLUSH,
	ENERGY_DEPLETION,
	COMPLETE,
}

const PHASE_DATA: Array[Dictionary] = [
	{
		"instruction": "> USE WASD OR ARROW KEYS TO MOVE YOUR SHIP",
		"condition": "move_distance",
		"threshold": 200.0,
	},
	{
		"instruction": "> PRESS 1, 2, OR 3 TO ACTIVATE YOUR WEAPONS\n> WATCH THE AUDIO LOOPS LAYER IN",
		"condition": "weapon_active",
		"threshold": 1,
	},
	{
		"instruction": "> NOTICE YOUR ELECTRIC BAR DRAINING\n> WEAPONS CONSUME ENERGY WHILE ACTIVE",
		"condition": "electric_below",
		"threshold": 0.8,
	},
	{
		"instruction": "> PRESS E TO ACTIVATE YOUR POWER CORE\n> IT REGENERATES ENERGY BUT GENERATES HEAT",
		"condition": "core_active",
		"threshold": 1,
	},
	{
		"instruction": "> YOUR THERMAL BAR IS RISING\n> HEAT IS GENERATED BY CORES AND SOME WEAPONS",
		"condition": "thermal_above",
		"threshold": 0.3,
	},
	{
		"instruction": "> TURN OFF ALL HEAT-GENERATING COMPONENTS\n> PRESS C TO DEACTIVATE ALL WEAPONS\n> HEAT ONLY DROPS WHEN ALL SOURCES ARE OFF",
		"condition": "thermal_dropping",
		"threshold": 0.0,
	},
	{
		"instruction": "> PRESS V FOR EMERGENCY THERMAL PURGE\n> THIS RAPIDLY VENTS ALL HEAT\n> BUT ENGINES STALL DURING THE PURGE",
		"condition": "purge_triggered",
		"threshold": 0.0,
	},
	{
		"instruction": "> NOW ACTIVATE EVERYTHING AND LET ENERGY DEPLETE\n> WHEN ENERGY RUNS OUT:\n>   - SHIELDS DRAIN FIRST\n>   - ENGINES SLOW DOWN\n>   - SHIP MAY SHUT DOWN COMPLETELY\n> MANAGE YOUR POWER CAREFULLY!",
		"condition": "electric_below",
		"threshold": 0.05,
	},
]

var _player: Node2D = null
var _hud: Control = null
var _game: Node2D = null
var _current_phase: int = 0
var _phase_timer: float = 0.0
var _instruction_label: RichTextLabel = null
var _start_position: Vector2 = Vector2.ZERO
var _move_distance: float = 0.0
var _prev_thermal: float = 0.0
var _typing_idx: int = 0
var _typing_timer: float = 0.0
var _current_text: String = ""
var _target_text: String = ""
var _phase_announced: bool = false
var _condition_met: bool = false
var _post_condition_timer: float = 0.0  # Brief pause after condition met before advancing


func setup(player: Node2D, hud: Control, game: Node2D) -> void:
	_player = player
	_hud = hud
	_game = game
	_start_position = player.position
	_prev_thermal = player.thermal if "thermal" in player else 0.0
	_build_instruction_ui()
	_announce_phase()


func _build_instruction_ui() -> void:
	_instruction_label = RichTextLabel.new()
	_instruction_label.bbcode_enabled = true
	_instruction_label.scroll_active = false
	_instruction_label.fit_content = true
	_instruction_label.position = Vector2(100, 650)
	_instruction_label.size = Vector2(700, 300)
	_instruction_label.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_instruction_label.z_index = 60
	var font: Font = ThemeManager.get_font("font_mono")
	if font:
		_instruction_label.add_theme_font_override("normal_font", font)
	_instruction_label.add_theme_font_size_override("normal_font_size", 18)
	_instruction_label.add_theme_color_override("default_color", Color(0.3, 1.0, 0.4))
	_game.add_child(_instruction_label)


func _announce_phase() -> void:
	if _current_phase >= PHASE_DATA.size():
		_show_complete()
		return
	var data: Dictionary = PHASE_DATA[_current_phase]
	_target_text = str(data.get("instruction", ""))
	_current_text = ""
	_typing_idx = 0
	_typing_timer = 0.0
	_phase_announced = true
	_condition_met = false
	_post_condition_timer = 0.0


func process(delta: float) -> void:
	if _current_phase >= PHASE_DATA.size():
		return

	_phase_timer += delta

	# Type instruction text
	if _phase_announced and _typing_idx < _target_text.length():
		_typing_timer += delta
		while _typing_timer >= 0.02 and _typing_idx < _target_text.length():
			_typing_timer -= 0.02
			_typing_idx += 1
			_current_text = _target_text.substr(0, _typing_idx)
		_instruction_label.text = "[color=#4dff66]" + _current_text + "[/color]"

	# Check condition
	if not _condition_met:
		_condition_met = _check_condition()
		if _condition_met:
			_post_condition_timer = 0.0
	else:
		_post_condition_timer += delta
		if _post_condition_timer >= 1.5:
			_advance_phase()


func _check_condition() -> bool:
	if not _player:
		return false
	var data: Dictionary = PHASE_DATA[_current_phase]
	var condition: String = str(data.get("condition", ""))
	var threshold: float = float(data.get("threshold", 0.0))

	match condition:
		"move_distance":
			_move_distance += _player.position.distance_to(_start_position)
			_start_position = _player.position
			return _move_distance >= threshold
		"weapon_active":
			var active_count: int = 0
			if _player._hardpoint_controller and _player._hardpoint_controller.has_method("get_active_count"):
				active_count = _player._hardpoint_controller.get_active_count()
			return active_count >= int(threshold)
		"electric_below":
			var elec: float = _player.electric
			var elec_max: float = _player.electric_max
			if elec_max <= 0.0:
				return false
			return (elec / elec_max) <= threshold
		"core_active":
			if _player._device_controller and _player._device_controller.has_method("has_active_core"):
				return _player._device_controller.has_active_core()
			return false
		"thermal_above":
			var therm: float = _player.thermal
			var therm_max: float = _player.thermal_max
			if therm_max <= 0.0:
				return false
			return (therm / therm_max) >= threshold
		"thermal_dropping":
			var therm: float = _player.thermal
			var dropping: bool = therm < _prev_thermal - 0.01
			_prev_thermal = therm
			return dropping
		"purge_triggered":
			if _player.has_meta("purge_triggered"):
				return true
			return false
	return false


func _advance_phase() -> void:
	phase_completed.emit(_current_phase)
	_current_phase += 1
	_phase_timer = 0.0
	_move_distance = 0.0
	_announce_phase()


func _show_complete() -> void:
	_instruction_label.text = "[color=#4dff66]> TUTORIAL COMPLETE\n> YOU ARE READY FOR COMBAT\n\n[color=#8888aa]PRESS ESC TO RETURN[/color][/color]"
	tutorial_complete.emit()
